---
# iptables setup
- name: Install iptables-persistent
  apt:
          name: iptables-persistent
          state: latest

#sudo iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
- name: Allow current SSH connection
  iptables:
          chain: INPUT
          match: conntrack
          ctstate: ESTABLISHED,RELATED
          jump: ACCEPT

#sudo iptables -A INPUT -p tcp --dport 22 -j ACCEPT
- name: Allow SSH connections
  iptables:
          chain: INPUT
          protocol: tcp
          destination_port: 22
          jump: ACCEPT


#sudo iptables -A INPUT -p tcp --dport 80 -j ACCEPT
- name: Allow HTTP connections
  iptables:
          chain: INPUT
          protocol: tcp
          destination_port: 80
          jump: ACCEPT

#sudo iptables -A INPUT -p tcp --dport 19999 -j ACCEPT
- name: Allow Netdata from internal network
  iptables:
          chain: INPUT
          protocol: tcp
          destination_port: 19999
          source: "{{ item }}"
          jump: ACCEPT
  with_items:
          - 10.0.0.0/24
          - 10.1.0.0/24

#sudo iptables -A INPUT -p udp --dport 1194 -j ACCEPT
- name: Allow OpenVPN connections
  iptables:
          chain: INPUT
          protocol: udp
          destination_port: 1194
          jump: ACCEPT

#sudo iptables -I INPUT 1 -i lo -j ACCEPT
- name: Allow loopback connections
  iptables:
          chain: INPUT
          in_interface: lo
          jump: ACCEPT
          action: insert
          rule_num: 1

#sudo iptables -P INPUT DROP
- name: Drop any remaining packets
  iptables:
          chain: INPUT
          jump: DROP

- name: netfilter-persistent save
  command: netfilter-persistent save
  
- name: netfilter-persistent reload
  command: netfilter-persistent reload
